### ISSUE TITLE
SUGGESTION: Remove language from release name

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/contextionary#27]
Currently, a release is tagged like [`en0.10.0-v0.4.5`](https://api.github.com/repos/semi-technologies/contextionary/releases/latest). However, it should be language agnostic, right?

I'm using the Github API to determine the latest release and add the language like `lang + getLatestC11y()`

**Comment by etiennedi** [comment]
Makes sense, let's start that with change proposed in #28. Closing here.
