### ISSUE TITLE
Allow for adding a word to the C11y

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/contextionary#8]
Especially for abbreviations or words specific for a use case. Users should be able to add words.

`$ POST /v1/c11y/words -d { TBD }`

Users should be able to define and weigh them accordingly based on a properly defined interface (TBD).

**Comment by fefi42** [comment]
Adding could be realized by synonyms.
The c11y knows `kebab` but not `kebap` so a synonym could be created.

What would be even nicer than just 1 to 1 synonyms, would be a combined vector e.g.:
`5starHotel` -> `['hotel', 'expensive', 'star', 'aaa']`
This could for the start be just implemented as a usual camelCase concat synonym.

**Comment by etiennedi** [comment]
## API Proposal

API assumes Weaviate API, what the actual c11y API to Weaviate looks like doesn't matter from a user's perspective:

The endpoint acts as an idempotent upsert, i.e. it doesn't know or care if the synoym already exists, if yes it will overwrite it:

```
PUT /v1/c11y/synonyms/<nameOfSynonym>
{
  "concepts": []string
}
```

This would work for both the exact synonym case:
```
PUT /v1/c11y/synonyms/kebap
{
  "concepts": ["kebab"]
}
```
as well as for the description:
```
PUT /v1/c11y/synonyms/5starHotel
{
  "concepts": ["hotel", "expensive", "star", "aaa"]
}
```
